I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 621, in script
    fuyu "Okay then, I don't see why not."
Exception: Sayer 'fuyu' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 621, in script
    fuyu "Okay then, I don't see why not."
  File "C:\Users\Nix\Downloads\renpy-8.0.3-sdk\renpy\ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Nix\Downloads\renpy-8.0.3-sdk\renpy\ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'fuyu' is not defined.

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.3.22090809
Epithets 1.0
Mon Feb  6 16:13:57 2023
